version: "3.8"

services:
  homecloud-backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../data:/app/data
      - ../.env:/app/.env # Mount env file into container
    environment:
      - PORT=3000
      - BASE_DIRECTORY=/app/data
